name: Create Build Artefacts

on:
    workflow_call:
        inputs:
            release_tag:
                required: true
                type: string

jobs:
    create-build-artifacts:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [16.x]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: npm ci
            - run: npm run package
              env:
                  RELEASE_TAG: ${{ inputs.release_tag }}

            - uses: actions/upload-artifact@v3
              with:
                  name: lox-lsp
                  path: "*.vsix"
